### PR TITLE
Fix "err is not defined"

### PR DESCRIPTION
**Pull request by Miosame**

### CODE REVIEW

**Review by gmicek — APPROVED** [review]

**Comment by gmicek** [comment]
This looks good. Please merge

**Comment by gmicek** [comment]
cc @JoeScho for merging

**Comment by JoeScho** [comment]
This is great - thank you @Miosame and @gmicek

**Comment by Miosame** [comment]
@gmicek thanks for bumping and @JoeScho thanks for merging :partying_face:

**Pull request merged**
